spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    host: smtp.gmail.com
    port: 587
    username: kangjideok@gmail.com
    password: truypwkqckapqsui
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
